### ISSUE TITLE
Command: [commands] output is not as expected, parsing error

### ISSUE THREAD

**Issue by sarveshwar-singh** [LA1TV/Hyperdeck-JS-Lib#36]
![1](https://user-images.githubusercontent.com/19986226/30420935-1f74da7a-9976-11e7-9aae-cbfe3a7f1471.png)
![2](https://user-images.githubusercontent.com/19986226/30420939-22809c7c-9976-11e7-9ce0-f75933023b83.png)

**Comment by sarveshwar-singh** [comment]
[**params**] does not contain XML string object

**Comment by joshhodgson** [comment]
According to the manual, **[commands]** is the only command in the protocol which doesn't comply with the response syntax below
```
{Response code} {Response text}:
{Parameter}: {Value}
{Parameter}: {Value}
...
```
The practical benefit of being able to parse the XML seems somewhat limited to me, given the detail in the manual. If you want to do a PR though, it will be merged!

**Comment by sarveshwar-singh** [comment]
It will save time of debugging for others.

**Comment by joshhodgson** [comment]
This is true. I'll reopen and eventually sort something if nobody beats me to it!

**Comment by sarveshwar-singh** [comment]
Thanks !!

Up next, 
https://github.com/LA1TV/Hyperdeck-JS-Lib/issues/38
